In [1]:
import numpy as np
import sys

**Note:**
References: (https://numpy.org/doc/stable/index.html)

## Intro to Numpy

- Numpy is numerical library for scientific calculations
- Faster than list
- Using contiguous memory
- We can do: insertion, deletion, appending, concatenation, and lots more

## Applications of Numpy
- Mathematics (Matlab Replacement)
- Plotting (Matplotlib)
- Backend (Pandas, Connect 4, Digital Photogrphy)
- Machine Learning

## Array Basics 

In [8]:
# Create an numpy array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
# Get dimension
a.ndim

1

In [10]:
# Get shape
b.shape

(2, 3)

In [12]:
# Get type
a.dtype #default

dtype('int32')

In [17]:
# Specify datatype
c = np.array([1,2,3], dtype='int8')
c.dtype

dtype('int8')

In [20]:
# Get total of number
a.size

3

In [18]:
# Get size
c.itemsize

1

In [22]:
b.itemsize

8

In [21]:
# Get total size
c.nbytes

3

In [23]:
b.nbytes

48

## Accessing/Changing

In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
a.shape #(row, columns)

(2, 7)

In [28]:
# Get a spesific elements
a[1, 5]

13

In [29]:
a[1][5]

13

In [30]:
a[1, -2]

13

In [31]:
# Get a spesific rows
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
# Get a spesific columns
a[:, 2]

array([ 3, 10])

In [43]:
# Get range elements
a[0:1, 0:4]

array([[1, 2, 3, 4]])

In [48]:
a[0:1, 0:4:2]

array([[1, 3]])

In [54]:
a[1, 5] = 15
print(a)
print('-'*40)

a[:, 2] = 2
print(a)
print('-'*40)

a[:, 4] = [1, 2]
print(a)

[[ 1  2  2  1  5  6  7]
 [ 8  9  2  2 12 15 14]]
----------------------------------------
[[ 1  2  2  1  5  6  7]
 [ 8  9  2  2 12 15 14]]
----------------------------------------
[[ 1  2  2  1  1  6  7]
 [ 8  9  2  2  2 15 14]]


In [56]:
b = np.array([[[1, 2], [3, 4]],[[5, 6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [59]:
# Get spesific element
b[0,0,0]

1

In [60]:
b[0][0][0]

1

In [62]:
b[0,1,0]

3

In [63]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [64]:
b[0,:,0]

array([1, 3])

In [71]:
# Replace
b[:,1,:] = [[1,1], [2,2]]
b[:,1,:]

array([[1, 1],
       [2, 2]])

## Different Types

In [81]:
np.zeros(1)

array([0.])

In [76]:
# All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [78]:
# All 1s matrix
np.ones((3,3,3), dtype='int16')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [90]:
# Any other numbers
np.full((2,2), 22)

array([[22, 22],
       [22, 22]])

In [89]:
np.full((7,7), 7, dtype='float32')

array([[7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.]], dtype=float32)

In [91]:
# Any other numbers (full like)
np.full(a.shape, 2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [96]:
np.full_like(a, 2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [100]:
# Random decimal numbers
np.random.rand(2,3,4)

array([[[0.7498884 , 0.35729846, 0.72539172, 0.58261255],
        [0.67106903, 0.81319429, 0.52571158, 0.86163272],
        [0.16113244, 0.90005464, 0.90033174, 0.64450466]],

       [[0.7940865 , 0.82633306, 0.92898085, 0.74149813],
        [0.23210469, 0.86719875, 0.41724198, 0.5741924 ],
        [0.70423506, 0.59869446, 0.67287472, 0.0238289 ]]])

In [113]:
# Random integer numbers
np.random.randint(10, size=(3,3)) #default 0-n

array([[2, 7, 4],
       [9, 6, 7],
       [4, 1, 0]])

In [114]:
np.random.randint(-10, 10, size=(3,3))

array([[-9, -1, -1],
       [ 5,  5,  5],
       [-2,  6,  3]])

In [115]:
# Identitity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [121]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [125]:
arr = np.array([[1,2,3]])
r2 = np.repeat(arr, 3, axis=0)
r2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Exploratory Array

In [132]:
output = np.zeros((5, 5))
output

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [133]:
output[1:4, 1:4] = 1
output

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [135]:
output[2,2] = 2
output

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 2., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

**Note:** Be carefull when copying arrays

In [136]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [137]:
y = x
y

array([1, 2, 3])

In [139]:
y[0] = 100
y

array([100,   2,   3])

In [140]:
x

array([100,   2,   3])

**Note:**
- When we assigenment y = x, it means y and x will refer to the same array.
- Using copy instead to copy an array

In [141]:
x = np.array([1,2,3])
print(x)

y = x.copy()
print(y)

[1 2 3]
[1 2 3]


In [142]:
print(x)

y[0] = 100
print(y)

[1 2 3]
[100   2   3]


## Mathematics

In [151]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [152]:
# do calculations to each elements
print(x + 1)
print(x - 2)
print(x * 3)
print(x / 4)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]


In [153]:
y = np.array([7, 8, 9])
y

array([7, 8, 9])

In [156]:
# do calculation between two or more arrays
print(x + y)
print(x * y)
print(x ** y)

[ 8 10 12]
[ 7 16 27]
[    1   256 19683]


In [158]:
# take the math val
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]


## Linear Algebra

In [162]:
x = np.ones((2, 3))
print(x)

y = np.full((3, 2), 2)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [168]:
# matrix operation
print(np.matmul(x, y))
print(np.matmul(y, x))

[[6. 6.]
 [6. 6.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [171]:
z = np.identity(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [173]:
# determinan matrix
np.linalg.det(z)

1.0

**Note:**
References docs: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norme
- Inverse
- Etc..

## Statistics

In [178]:
s = np.array([[1,2,3], [4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [184]:
print(np.min(s)) #default
print(np.min(s, axis=1))

1
[1 4]


In [185]:
print(np.max(s)) #default
print(np.max(s, axis=1))

6
[3 6]


In [186]:
print(np.mean(s)) #default
print(np.mean(s, axis=1))

3.5
[2. 5.]


In [187]:
print(np.sum(s)) #default
print(np.sum(s, axis=1))

21
[ 6 15]


## Reorganizing Arrays

In [189]:
bef = np.array([[1,2,3,4], [5,6,7,8]])
bef

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [195]:
# reshape
aft = bef.reshape((4, 2))
aft

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [199]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [ ]:
# vertical stack
np.vstack([v1, v2])

In [200]:
# horizontal stack
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

## Miscallaneous

### Load data from file

In [205]:
data_number = np.genfromtxt('data/number.txt', delimiter=',')
data_number

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.],
       [21., 22., 23., 24.],
       [25., 26., 27., 28.],
       [29., 30., 31., 32.],
       [33., 34., 35., 36.],
       [37., 38., 39., 40.]])

In [207]:
data_number.dtype

dtype('float64')

In [209]:
data_number.astype('int8')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40]], dtype=int8)

In [206]:
data_people = np.genfromtxt('data/people.txt', delimiter=',')
data_people

array([[nan, nan, nan, nan, nan],
       [nan, 25., nan, nan, nan],
       [nan, 22., nan, nan, nan],
       [nan, 30., nan, nan, nan],
       [nan, 27., nan, nan, nan],
       [nan, 35., nan, nan, nan],
       [nan, 28., nan, nan, nan],
       [nan, 40., nan, nan, nan],
       [nan, 32., nan, nan, nan],
       [nan, 45., nan, nan, nan],
       [nan, 38., nan, nan, nan]])

In [210]:
data_people.dtype

dtype('float64')

### Boleean Masking

In [212]:
data_number > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [213]:
data_number[data_number > 20]

array([21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33.,
       34., 35., 36., 37., 38., 39., 40.])

**Note:** We can index with a list in numpy

In [214]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [218]:
# check whether any data is greater than 20
np.any(data_number > 20)

True

In [222]:
np.any(data_number > 20, axis=0) #check by columns

array([ True,  True,  True,  True])

In [221]:
np.any(data_number > 20, axis=1) #check by rows

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [219]:
# check all data which is greater than 20
np.all(data_number > 20)

False

In [223]:
np.all(data_number > 20, axis=0) #by columns

array([False, False, False, False])

In [225]:
np.all(data_number > 20, axis=1) #by rows

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [232]:
(data_number > 10) & (data_number < 30)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [236]:
# reverse
(~ (data_number > 10) & (data_number < 30))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## Practice

### 1. Generate matrix (values=1-30, size=6x5)

In [251]:
np.reshape([x for x in range(1, 31)], (6, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [250]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### 2. Indexing values 11 12 16 17 from the matrix

In [253]:
arr[2:4, 0:2]

array([[11, 12],
       [16, 17]])

### 3. Indexing values 2 8 14 20 from the matrix

In [257]:
np.diag(arr[0:4, 1:])

array([ 2,  8, 14, 20])

In [260]:
arr[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

### 4. Indexing values 4 5 24 25 29 30 from the matrix

In [267]:
arr[[0, -2, -1], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])